# Generated by Django 3.0.4 on 2020-08-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=40)),
                ('last_name', models.CharField(default='', max_length=40)),
                ('mob_num', models.CharField(default='', max_length=16)),
                ('job_title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('immediate_join', models.BooleanField(default=False)),
            ],
        ),
    ]
