# Generated by Django 3.0.4 on 2020-08-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobapplicant',
            table='Job Applicant',
        ),
    ]
